name: CD - Infrastructure Deploy
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  push:
    branches: [ main, develop ]

jobs:
  infra-check:
    name: ÐŸÑ€Ð¾Ð²ÐµÑ€ÐºÐ° Ð¸Ð½Ñ„Ñ€Ð°ÑÑ‚Ñ€ÑƒÐºÑ‚ÑƒÑ€Ñ‹
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare env file
        run: cp .env.infrastructure.example .env.infrastructure

      - name: Check redis.conf exists
        run: ls -la ./redis.conf

      - name: Validate docker-compose syntax
        run: docker compose -f docker-compose.infrastructure.yaml config

      - name: Build infrastructure images
        run: docker compose -f docker-compose.infrastructure.yaml build

      - name: Run infrastructure containers
        run: docker compose -f docker-compose.infrastructure.yaml --env-file .env.infrastructure  up -d

      - name: Check containers health
        run: |
          sleep 15
          docker ps
          docker compose ps
          docker compose -f docker-compose.infrastructure.yaml --env-file .env.infrastructure logs postgres
          docker compose -f docker-compose.infrastructure.yaml --env-file .env.infrastructure logs redis

      - name: Stop infrastructure containers
        run: docker compose -f docker-compose.infrastructure.yaml --env-file .env.infrastructure down -v

  deploy:
    name: ðŸš€ Deploy to server
    needs: infra-check
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            set -e
            cd /home/bot_server/test_zone/taxi_bot

            echo "Pulling latest code..."
            git fetch origin develop
            git reset --hard origin/develop

            echo "Building infrastructure..."
            docker compose -f docker-compose.infrastructure.yml up -d --build

            echo "Recreating app containers..."
            docker compose -f docker-compose.yml up -d --build

            echo "âœ… Deployment complete!"
          EOF